//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MCCSHynm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hymn
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int HynmNumber { get; set; }
        public string HynmVerse1 { get; set; }
        public string HymnChorus { get; set; }
        public string HynmClosing { get; set; }
        public string HynmVerse2 { get; set; }
        public string HymnVerse3 { get; set; }
        public string HymnVerse4 { get; set; }
        public string HymnVerse5 { get; set; }
    }
}
